export const mockDataTags = {
  items: [
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2528632,
      name: "javascript",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 7190,
      name: "javascript-objects",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 5319,
      name: "facebook-javascript-sdk",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 1010,
      name: "javascript-framework",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 845,
      name: "youtube-javascript-api",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 511,
      name: "unobtrusive-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 422,
      name: "javascriptserializer",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 416,
      name: "serverside-javascript",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 364,
      name: "javascript-debugger",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 358,
      name: "isomorphic-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 336,
      name: "javascriptcore",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 258,
      name: "javascript-automation",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 217,
      name: "javascript-intellisense",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 208,
      name: "javascript-injection",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 197,
      name: "rethinkdb-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 191,
      name: "javascriptmvc",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 173,
      name: "javascript-engine",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 169,
      name: "asynchronous-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 158,
      name: "javascript-namespaces",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 127,
      name: "javascript-import",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 76,
      name: "javascript-api-for-office",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 76,
      name: "javascript-databinding",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 71,
      name: "parse-javascript-sdk",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 66,
      name: "javascript-marked",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 63,
      name: "google-api-javascript-client",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 55,
      name: "clojurescript-javascript-interop",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 55,
      name: "embedded-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 50,
      name: "log4javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 45,
      name: "javascript-security",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 45,
      name: "javascript-function-declaration",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 43,
      name: "javascript-globalize",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 43,
      name: "javascript-decorators",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 39,
      name: "javascript-proxy",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 33,
      name: "javascript-scope",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 31,
      name: "shopify-javascript-buy-sdk",
    },
    {
      collectives: [
        {
          tags: [
            "twilio-functions",
            "sendgrid",
            "twilio-api",
            "twilio-programmable-voice",
            "twilio-node",
            "sendgrid-ruby",
            "twilio-click-to-call",
            "twilio-cli",
            "twilio-conference",
            "twilioflexwebchat",
            "twilio-javascript",
            "twilio-flex",
            "twilio-python",
            "twilio-studio",
            "authy",
            "twilio-taskrouter",
            "segment-io",
            "twilio-php",
            "sendgrid-rails",
            "twimlet",
            "sendgrid-templates",
            "twilio-amd",
            "twilio-programmable-chat",
            "twilio-conversations",
            "twilio",
            "twilio-video",
            "twilio-twiml",
            "sendgrid-api-v3",
            "sendgrid-api-v2",
          ],
          external_links: [
            {
              type: "website",
              link: "https://www.twilio.com/",
            },
            {
              type: "support",
              link: "mailto:stackoverflow@twilio.com",
            },
            {
              type: "twitter",
              link: "https://twitter.com/TwilioDevs",
            },
            {
              type: "github",
              link: "https://github.com/twilio",
            },
            {
              type: "facebook",
              link: "https://facebook.com/TeamTwilio",
            },
            {
              type: "instagram",
              link: "https://instagram.com/twilio",
            },
          ],
          description:
            "Twilio has democratized channels like voice, text, chat, video, and email by virtualizing the world’s communications infrastructure through APIs that are simple enough for any developer, yet robust enough to power the world’s most demanding applications.",
          link: "/collectives/twilio",
          name: "Twilio",
          slug: "twilio",
        },
      ],
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 31,
      name: "twilio-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 31,
      name: "javascript-audio-api",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 31,
      name: "adobe-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 30,
      name: "amazon-javascript-sdk",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 30,
      name: "esri-javascript-api",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 29,
      name: "evaluatejavascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 26,
      name: "javascript-inheritance",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 23,
      name: "android-webview-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 20,
      name: "javascriptexecutor",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 20,
      name: "javascript-oscillator",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 19,
      name: "javascript-interop",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 19,
      name: "ews-javascript-api",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 16,
      name: "keycloak-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 14,
      name: "braintree-javascript",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 14,
      name: "javascript-date",
    },
  ],
  has_more: true,
};
